name: terraform-apply-dev

on:
  workflow_dispatch:
  push:
    paths:
      - 'envs/dev/**.tf'
      - 'modules/**.tf'

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        working-directory: envs/dev
        run: terraform init

      - name: Terraform Validate
        working-directory: envs/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: envs/dev
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: envs/dev
        run: terraform apply -auto-approve tfplan
